### ISSUE TITLE
Issue in exporting the artist name

### ISSUE THREAD

**Issue by AnkitRajSri** [CUTR-at-USF/muser-firebase-export#10]
The app seems to be exporting the album names in place of the artist names.

**Comment by pradeepsalunke** [comment]
While inserting the records into Firebase DB  artist name is getting duplicated with album names.
Export app is working as expected.

**Comment by barbeau** [comment]
@pradeepsalunke Thanks for looking at this. Could you please open an issue on the MUSER app repository and link to this issue?

**Comment by barbeau** [comment]
Here's the MUSER app issue - https://github.com/CUTR-at-USF/MUSER/issues/134. This was fixed in the v1.3.0 release of the app.
